image: gcc

cache: 
  paths:
    - build/

build:
  stage: build

  before_script:
    - apt-get update && apt-get -y install make autoconf curl automake libtool g++ unzip
    - apt-get -y install cmake
    - apt-get -y install python3-dev
    - mkdir /protobuf
    - cd /protobuf
    - curl -L -o protobuf.zip https://github.com/protocolbuffers/protobuf/releases/download/v3.15.6/protobuf-cpp-3.15.6.zip 
    - unzip protobuf.zip
    - cd /protobuf/protobuf-3.15.6
    - ./configure
    - make
    - make check || true
    - make install
    - ldconfig
       
  script:
    - cd ${CI_PROJECT_DIR}
    - mkdir -p build
    - cd build
    - cmake ..
    - cmake --build .

pages:
  script:
  - apt-get update && apt-get install -y doxygen graphviz fonts-freefont-ttf
  - cd cTORS
  - doxygen Doxyfile
  - cd ..
  - mv cTORS/doc/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
