# This file is a template, and might need editing before it works on your project.
# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: gcc

build:
  stage: build
  # instead of calling g++ directly you can also use some build toolkit like make
  # install the necessary build tools when needed
  before_script:
    - apt-get update && apt-get -y install make autoconf
    - apt-get -y install cmake
    - apt-get -y install python3-dev
  script:
    - mkdir build
    - cd build
    - cmake ..
    - cmake --build .
  