# This file is a template, and might need editing before it works on your project.
# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: gcc

build:
  stage: build
  # instead of calling g++ directly you can also use some build toolkit like make
  # install the necessary build tools when needed
  before_script:
    - apt-get update && apt-get -y install make autoconf curl automake libtool g++ unzip
    - apt-get -y install cmake
    - apt-get -y install python3-dev
    - mkdir /protobuf
    - cd /protobuf
    - curl -L -o protobuf.zip https://github.com/protocolbuffers/protobuf/releases/download/v3.15.6/protobuf-cpp-3.15.6.zip 
    - unzip protobuf.zip
    - cd /protobuf/protobuf-3.15.6
    - ./configure
    - make
    - make check || true
    - make install
    - ldconfig
       
  script:
    - mkdir build
    - cd build
    - cmake ..
    - cmake --build .
  
